# Generated by Django 5.0.6 on 2024-07-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id_zapatilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('niño', 'Niño'), ('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='zapatillas_imagenes/')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
